[build]
target = "aarch64-unknown-linux-gnu"

[target.aarch64-unknown-linux-gnu]
linker = "/usr/bin/aarch64-linux-gnu-gcc"
rustflags = [
    "-C", "link-arg=-s",           # Strip
    "-C", "opt-level=z",           # Compression
]