name: Docker AArch64 Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t cyber-gpu-build .

      - name: Extract build output
        run: |
          docker create --name temp cyber-gpu-build
          docker cp temp:/cyber-gpu-test/target/aarch64-unknown-linux-gnu/release/cyber-gpu-test ./cyber-gpu-test
          docker rm temp

      - name: Archive binary to .tar.gz
        run: |
          tar -czvf cyber-gpu-test.tar.gz cyber-gpu-test

      - name: Upload artifact (binary)
        uses: actions/upload-artifact@v4
        with:
          name: cyber-gpu-test
          path: ./cyber-gpu-test

      - name: Upload artifact (archive)
        uses: actions/upload-artifact@v4
        with:
          name: cyber-gpu-test-archive
          path: ./cyber-gpu-test.tar.gz
