name: Cross Build (aarch64)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install cross
        run: cargo install cross

      - name: Cross build for aarch64
        run: cross build --target aarch64-unknown-linux-gnu --release
