name: Rust (aarch64-unknown-linux-gnu)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust target
        run: rustup target add aarch64-unknown-linux-gnu

      - name: Install cross-compilation tools
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Set up .cargo/config.toml
        run: |
          mkdir -p .cargo
          echo '[target.aarch64-unknown-linux-gnu]' > .cargo/config.toml
          echo 'linker = "/usr/bin/aarch64-linux-gnu-gcc"' >> .cargo/config.toml

      - name: Build (release)
        run: cargo build --verbose --release --target aarch64-unknown-linux-gnu

      # Tests are skipped since they can't run for aarch64 cross-build
      - name: Run tests (native only)
        if: false
        run: cargo test --verbose
